### ISSUE TITLE
Add feasibility to comment the environment configs in .env.config file

### ISSUE THREAD

**Issue by suthagar23** [APISquare/envone#12]
The current implement doesn't allow to add comments to the `.env.config` file as follows,

```
{
  "HOST": "https://abc.com",
  // "SERVER_URL": "{{BASE_URL}}/api/v1",
}
```

Related error : 

```
[Configured Env]  {
  error: SyntaxError: Unexpected token / in JSON at position 4
      at JSON.parse (<anonymous>)
      at Object.module.exports.config (/home/APISquare/envone/example/node_modules/envone/src/config.js:136:38)
      at Object.<anonymous> (/home/APISquare/envone/example/index.js:12:41)
      at Module._compile (internal/modules/cjs/loader.js:1075:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
      at Module.load (internal/modules/cjs/loader.js:940:32)
      at Function.Module._load (internal/modules/cjs/loader.js:781:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
      at internal/main/run_main_module.js:17:47
}
```

**Comment by mjnagel** [comment]
@suthagar23 since JSON does not support comments are you looking to switch to using something other than JSON or make use of a workaround in JSON to allow comments? I could look into a yml alternative instead or you could go with a format like this:
```
{
  "HOST": "https://abc.com",
  "__SERVER_URL__": "{{BASE_URL}}/api/v1",
}
```

It's not the clearest or cleanest but if well documented you can make it clear to use that format for comments. Happy to work on this if you have an opinion on either way.

**Comment by suthagar23** [comment]
Hi @mjnagel, First thanks for your interest in this. 

Yes, I also would like to have a YML alternative for this (So users can use `.env.config` or `.env.yml`). If you want, I can able to create an issue as a new feature and add that. But it might be a huge wight task and needs to be unit tested as well :-) 

---
Next for the above issue,
The problem occurs when we parse the `.env.config` content in this following way,
```
const parsedData = parseEnv(JSON.parse(fs.readFileSync(configPath, { encoding: "utf8" })));
```

So if we are able to add a wrapper to read and remove the commented line(s) from the read file before parsing it, that would be the solution for this. 

```
function parseReadFile(content) {
  // remove commented line or lines
}

const parsedData = parseEnv(JSON.parse(parseReadFile(fs.readFileSync(configPath, { encoding: "utf8" }))));
```

**Comment by mjnagel** [comment]
Okay, I see now! Yes I'd be happy to make a parser to remove the comments if you'd like to assign it to me. I'll have to spend a little time just making sure I follow your code's current formatting and structure but I'd be happy to tackle this.

Totally agree a YML alternative would be a big leap!

**Comment by suthagar23** [comment]
I have assigned this task to you. Hope to see your plan soon :-)

**Comment by mjnagel** [comment]
@suthagar23 what's the easiest way to test / test if my changes have the desired effect? Working through a func that I think should work...

**Comment by mjnagel** [comment]
@suthagar23 I did some initial testing and this PR should add support for single comments like the example you provided in the issue. Not sure if you're looking for something more in depth to support more types of comments? Happy to expand the solution as needed.

**Comment by suthagar23** [comment]
Yes, as the first step we can add single line comments and can extend up to multi-line comments later.
